spring:
    application:
        name: account-product-manager
    
    output:
        ansi:
            enabled: ALWAYS

server:
    port: 8080                  # default - 8080, change if ports conflict